### ISSUE TITLE
Investigate supporting JavaCPP

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire-java#2]
More details here:
https://github.com/arrayfire/arrayfire/issues/155

**Comment by saudet** [comment]
Hey guys, let me know if this becomes a priority in some way. I don't have a lot of time at the moment, but if it's important enough, as the author of JavaCPP, I could give a hand with this.

**Comment by pavanky** [comment]
@saudet We are proceeding with using plain JNI right now.  I have not looked yet looked into JavaCPP but I'll experiment a bit and see if it'll help us out.

**Comment by saudet** [comment]
JavaCPP is basically a tool to help generate efficient JNI for existing C++ API, along with a few helper Java classes that are usually required anyway. It's still not perfect obviously, but that's essentially what it is.

**Comment by pavanky** [comment]
I think our C API is more convenient for us right now. So we'll need to continue with JNI for now.
